### ISSUE TITLE
A quick start?

### ISSUE THREAD

**Issue by smilingpoplar** [bytesnake/mdbook-scientific#1]
I couldn't `cargo install` it. When I `cargo build`, here's the error:
```
error[E0599]: no method named `input` found for struct `sha2::Sha256` in the current scope
  --> src/fragments.rs:13:8
   |
13 |     sh.input(input.as_bytes());
   |        ^^^^^ method not found in `sha2::Sha256`

error[E0599]: no method named `result` found for struct `sha2::Sha256` in the current scope
  --> src/fragments.rs:14:38
   |
14 |     let mut out = format!("{:x}", sh.result());
   |                                      ^^^^^^ method not found in `sha2::Sha256`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `mdbook-scientific`.
```

**Comment by bruceloco** [comment]
/// Convert input string to 24 character hash
pub fn hash(input: &str) -> String {
let mut sh = Sha256::new();
sh.input(input.as_bytes());
let mut out = format!("{:x}", sh.result());
out.truncate(24);
out
}

Does not build, input and result are not registered apis

changed to
/// Convert input string to 24 character hash
pub fn hash(input: &str) -> String {
let mut sh = Sha256::new();
sh.update(input.as_bytes());
let mut out = format!("{:x}", sh.finalize());
out.truncate(24);
out
}
